### ISSUE TITLE
Reconsider adding scales to the piano view

### ISSUE THREAD

**Issue by sluedecke** [tckmn/semitone#9]
Hi,

First thanks for merging parts of my pull request. You deliberately omitted the scale highlighting, stating that you want to keep semitone simple.

I am new to music theory and I learn a lot about intervals, scales and such. For me having such a feature greatly enhances my learning, because I can play around with a certain scale on any root note without having to memorize all notes upfront. I can try out melodies, chords and whatnot to experience a certain scale.

Semitone proved to be an easy way to have such a feature which I did not find in the other piano like apps (maybe I missed it?).

So I kindly ask to reconsider integrating it. Maybe you want to have it integrated in the ui some other way or make it a truly (needs enablement in the settings) optional feature?

**Comment by tckmn** [comment]
Hello,

As a relative beginner to music theory myself, I appreciate the usefulness of a feature that would make it easier to learn how different kinds of scales work. However, the purpose of Semitone is not to be a music learning app, and the same kind of argument could be made for, say, a feature that lets you play chords, or prerecorded songs that you can play along to. In the interest of keeping the app uncluttered and lightweight, I'd prefer to avoid this kind of feature creep.

While I'd rather not include these features in the app itself, since Semitone is licensed under GPL, you can feel free to copy the code for the piano and include it in a different app that could be focused more on learning music theory, rather than designed as a tool for helping musicians (as long as the other app is GPL-licensed as well).

Thanks again for your time and contributions.
